// src/Stubs/resources/js/pages/builder/create.tsx
import { ColumnDef, FieldDefinition } from "@/types/field-builder";
import { AppFormBuilder } from "@/components/builder/app-form-builder";
import AppLayout from "@/layouts/app-layout";
import { Head } from "@inertiajs/react";
import { BreadcrumbItem } from "@/types";
import { Card, CardContent } from "@/components/ui/card";
import { route } from "ziggy-js";

type Form = {
    columns: ColumnDef;
    fields: FieldDefinition[];
};

type PageProps = {
    form: Form;
    routeName: string;
    formClass: string;
};

export default function Create({ form, routeName, formClass }: PageProps) {
    const { columns, fields } = form;
    const breadcrumbs: BreadcrumbItem[] = [
        { title: `${routeName}`, href: route(routeName + ".index") },
        { title: 'new', href: route(routeName + ".create") },
        { title: '#', href: '' },
    ];
    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title={`new ${routeName}`} />
            <div className="p-4">
                <Card className="p-4 max-w-full">
                    <CardContent>
                        <AppFormBuilder columns={columns} fields={fields} routeName={routeName} mode="create" formClass={formClass} />
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}

// src/Stubs/vue/resources/js/pages/builder/create.vue
<script lang="ts" setup>
import AppFormBuilder from "@/components/builder/AppFormBuilder.vue";
import AppLayout from "@/layouts/AppLayout.vue";
import { Head } from "@inertiajs/vue3";
import { Card, CardContent } from "@/components/ui/card";
import { route } from "ziggy-js";
import AppFormBuilderAction from "@/components/builder/form/AppFormBuilderAction.vue";
import type { Form } from "@/types/form";
import type { BreadcrumbItem } from "@/types";
import { useFormStore } from "@/stores/form";

// Props
interface Props {
    form: Form;
}
const props = defineProps<Props>();

const { baseRoute, title, prefix } = props.form;

const idx = `${prefix}-create}`;
const store = useFormStore(idx)();
store.setData(props.form);

const breadcrumbs: BreadcrumbItem[] = [
    { title: title, href: route(baseRoute + ".index") },
    { title: "new", href: route(baseRoute + ".create") },
    { title: "#", href: "" },
];

</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">

        <Head :title="`new ${title}`" />
        <div class="p-4">
            <Card class="p-4 max-w-full">
                <CardContent>
                    <AppFormBuilder :form="props.form" :idx="idx">
                        <template #formAction>
                            <AppFormBuilderAction :form="props.form" :idx="idx" />
                        </template>
                    </AppFormBuilder>
                </CardContent>
            </Card>
        </div>
    </AppLayout>
</template>
