// src/Stubs/resources/js/pages/builder/edit.tsx
import { Head } from '@inertiajs/react';
import AppLayout from "@/layouts/app-layout";
import { BreadcrumbItem } from "@/types";
import { AppFormBuilder } from "@/components/builder/app-form-builder";
import { Card, CardContent } from "@/components/ui/card";
import { route } from "ziggy-js";
import { Form } from '@/types/form';
import { AppFormBuilderAction } from '@/components/builder/form/action';

type PageProps = {
    form: Form;
};

export default function Edit({ form }: PageProps) {
    const { baseRoute, routeId, title } = form;

    const breadcrumbs: BreadcrumbItem[] = [
        { title: title, href: route(baseRoute + ".index") },
        { title: 'edit', href: route(baseRoute + ".edit", routeId) },
        { title: `#${routeId}`, href: '' }
    ];

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title={`edit ${title} #${routeId}`} />
            <div className="p-4">
                <Card className="p-4 max-w-full">
                    <CardContent>
                        <AppFormBuilder form={form}>
                            {{
                                formAction: (processing) => (
                                    <AppFormBuilderAction form={form} processing={processing} />
                                )
                            }}
                        </AppFormBuilder>
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}

// src/Stubs/vue/resources/js/pages/builder/edit.vue
<script lang="ts" setup>
import { Head } from '@inertiajs/vue3';
import AppLayout from "@/layouts/AppLayout.vue";
import AppFormBuilder from "@/components/builder/AppFormBuilder.vue";
import { Card, CardContent } from "@/components/ui/card";
import AppFormBuilderAction from "@/components/builder/form/AppFormBuilderAction.vue";
import { route } from "ziggy-js";
import type { Form } from '@/types/form';
import type { BreadcrumbItem } from "@/types";
import { useFormStore } from '@/stores/form';

// Props
interface Props {
    form: Form;
}
const props = defineProps<Props>();

const { baseRoute, routeId, title, prefix } = props.form;

const idx = `${prefix}-edit}`;
const store = useFormStore(idx)();
store.setData(props.form);

const breadcrumbs: BreadcrumbItem[] = [
    { title: title, href: route(baseRoute + ".index") },
    { title: 'edit', href: route(baseRoute + ".edit", routeId) },
    { title: `#${routeId}`, href: '' },
];

</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">

        <Head :title="`edit ${title} #${routeId}`" />
        <div class="p-4">
            <Card class="p-4 max-w-full">
                <CardContent>
                    <AppFormBuilder :form="props.form" :idx="idx">
                        <template #formAction>
                            <AppFormBuilderAction :form="props.form" :idx="idx" />
                        </template>
                    </AppFormBuilder>
                </CardContent>
            </Card>
        </div>
    </AppLayout>
</template>
