// src/Stubs/resources/js/pages/builder/index.tsx
import React from 'react';
import { Head } from '@inertiajs/react';
import AppDataTable from "@/components/builder/app-datatable";
import AppLayout from "@/layouts/app-layout";
import { BreadcrumbItem } from "@/types";
import { DataTableProps } from "@/types/datatable";
import AppDatatableRowActions from '@/components/builder/table/row-actions';
import { route } from 'ziggy-js';

interface Props {
    data: DataTableProps;
}

export default function Index({ data }: Props) {
    const { baseRoute, tableRoute, title } = data
    const routeUrl = tableRoute ? tableRoute : route(baseRoute + ".index")

    const breadcrumbs: BreadcrumbItem[] = [
        {
            title: title,
            href: routeUrl,
        },
    ];
    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title={title} />
            <div className="p-4">
                <AppDataTable data={data}>
                    {{
                        rowAction: (item) => (
                            <AppDatatableRowActions
                                item={item}
                                baseRoute={data.baseRoute}
                                edit={data.edit}
                                show={data.view}
                                del={data.delete}
                            />
                        ),
                        toolbarAction: (
                            <>
                            </>
                        ),
                    }}
                </AppDataTable>
            </div>
        </AppLayout>
    );
}

// src/Stubs/vue/resources/js/pages/builder/index.vue
<script setup lang="ts">
import AppLayout from '@/layouts/AppLayout.vue';
import { BreadcrumbItem } from '@/types';
import { Head } from '@inertiajs/vue3';
import { DataTableProps } from "@/types/datatable";
import { route } from 'ziggy-js';
import AppDataTable from "@/components/builder/AppDataTable.vue";
import AppDataTableRowActions from "@/components/builder/table/AppDataTableRowActions.vue";
import { useDatatableStore } from '@/stores/datatable';

const props = defineProps<{
    data: DataTableProps;
}>();

// initialize table store
const idx = `${props.data.prefix}-${props.data.name}`;
const store = useDatatableStore(idx)();
store.setData(props.data);

const { baseRoute, tableRoute, title } = props.data;
const routeUrl = tableRoute ? tableRoute : route(baseRoute + ".index")

const breadcrumbs: BreadcrumbItem[] = [
    {
        title: title,
        href: routeUrl,
    },
];

</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">

        <Head :title="title" />
        <div className="p-4">
            <AppDataTable :idx="idx">
                <template #rowAction="{ item }">
                    <AppDataTableRowActions :item="item" :idx="idx" />
                </template>

                <template #toolbarAction>
                </template>
            </AppDataTable>
        </div>
    </AppLayout>
</template>
