// src/Stubs/vue/resources/js/components/builder/AppDataTable.vue
<script setup lang="ts">
import { DataItem, DataTableProps } from '@/types/datatable';
import { router, usePage } from '@inertiajs/vue3';
import { watch } from "vue";
import { route } from 'ziggy-js';
import AppDataTableContent from './table/AppDataTableContent.vue';
import AppDataTablePagination from './table/AppDataTablePagination.vue';
import AppDataTableToolbar from './table/AppDataTableToolbar.vue';
import AppDataTableActiveFilters from './table/AppDataTableActiveFilters.vue';
import { useFlashStore } from '@/stores/flash';
import { useDatatableStore } from '@/stores/datatable';
import { storeToRefs } from 'pinia';
import { ref } from 'vue';

type RespProp = {
    data: DataTableProps,
};

defineSlots<{
    rowAction?: { item: DataItem }
    toolbarAction?: () => any
}>();

const props = defineProps<{
    idx: string;
}>();

const store = useDatatableStore(props.idx)();

const name = store.tableData.name;
const prefix = store.tableData.prefix;
const disablePagination = store.tableData.disablePagination;

// --- watch flash
const flashStore = useFlashStore();
const page = usePage()

watch(
    () => page.props.flash,
    (flash) => {
        if (flash) {
            flashStore.setFlash(flash)
        }
    },
    { immediate: true }
)


// --- watch filters, sort, query ---
const { sort, dir, searchQuery, activeFilters } = storeToRefs(store);
const firstRender = ref(true);
watch([sort, dir, searchQuery, activeFilters], ([s, d, q, af], _, onCleanup) => {
    if (firstRender.value) {
        firstRender.value = false;
        return;
    }

    const handler = setTimeout(() => {
        const filterParams = af.reduce((acc, filter) => {
            if (filter.value && Array.isArray(filter.value) && filter.value.length > 0) {
                const joined = filter.value.length > 1 ? filter.value.join(",") : filter.value.toString();
                acc[`${prefix}filter[${filter.field}]`] = filter.operator ? `${filter.operator}:${joined}` : joined;
            } else if (filter.value) {
                acc[`${prefix}filter[${filter.field}]`] = filter.operator
                    ? `${filter.operator}:${filter.value}`
                    : (filter.value as string);
            }
            return acc;
        }, {} as Record<string, string>);

        const params = Object.keys(filterParams).length > 0 ? filterParams : {};

        const routeUrl = store.tableData.tableRoute
            ? store.tableData.tableRoute
            : route(`${store.tableData.baseRoute}.index`);

        const searchParam = prefix + "q";
        const sortByParam = prefix + "sort";
        const sortDirParam = prefix + "dir";

        router.get(
            routeUrl,
            {
                ...(params ? { ...params } : {}),
                [searchParam]: q,
                [sortByParam]: s,
                [sortDirParam]: d,
            },
            {
                preserveScroll: true,
                preserveState: true,
                only: [name],
                onSuccess: (page) => {
                    const props = page.props as unknown as RespProp;
                    store.updateItems(props.data.items);
                }
            }
        );
    }, 350);

    onCleanup(() => clearTimeout(handler));
});

</script>

<template>
    <div class="overflow-auto rounded-xl border bg-background text-foreground shadow-sm">
        <AppDataTableToolbar :idx="idx">
            <template #toolbarAction>
                <slot name="toolbarAction" />
            </template>
        </AppDataTableToolbar>
        <AppDataTableActiveFilters :idx="idx" />
        <AppDataTableContent :idx="idx">
            <template #rowAction="{ item }">
                <slot name="rowAction" :item="item" />
            </template>
        </AppDataTableContent>

        <AppDataTablePagination v-if="!disablePagination" :idx="idx" />
    </div>
</template>

// src/Stubs/resources/js/components/builder/app-datatable.tsx
import { AppDataTableActiveFilters } from '@/components/builder/table/active-filters';
import { ActiveFilter, DataItem, DataTableProps } from '@/types/datatable';
import { router, usePage } from '@inertiajs/react';
import { useEffect, useRef, useState } from 'react';
import { toast } from 'sonner';
import { AppDataTableContent } from './table/content';
import { AppDataTablePagination } from './table/pagination';
import { AppDataTableToolbar } from './table/toolbar';
import { route } from 'ziggy-js';

type DataTable = {
    data: DataTableProps;
    children?: {
        rowAction?: (item: DataItem) => React.ReactNode;
        toolbarAction?: React.ReactNode;
    };
};

export default function AppDataTable({ data, children }: DataTable) {
    const { name, prefix, items, filters, columns, disablePagination } = data;
    const [openFilterPopovers, setOpenFilterPopovers] = useState<Record<string, boolean>>({});
    const openPopover = (field: string) => setOpenFilterPopovers((prev) => ({ ...prev, [field]: true }));
    const closePopover = (field: string) => setOpenFilterPopovers((prev) => ({ ...prev, [field]: false }));

    const { flash } = usePage().props as { flash?: { success?: string; error?: string; description?: string } };

    const [selectedIds, setSelectedIds] = useState<(string | number)[]>([]);

    const [hiddenColumns, setHiddenColumns] = useState<Record<string, boolean>>(() => {
        const initial: Record<string, boolean> = {};
        columns.forEach((col) => {
            initial[col.name] = col.hidden;
        });
        return initial;
    });
    const toggleColumn = (colName: string) => {
        setHiddenColumns((prev) => ({
            ...prev,
            [colName]: !prev[colName],
        }));
    };

    const initialActiveFilters: ActiveFilter[] = [];
    if (filters.filter) {
        Object.entries(filters.filter).forEach(([field, value]) => {
            const operator = value.split(':')[0];
            const filterValue = value.split(':')[1];
            initialActiveFilters.push({ field, operator, value: filterValue });
        });
    }
    const [activeFilters, setActiveFilters] = useState<ActiveFilter[]>(initialActiveFilters);

    const [searchQuery, setSearchQuery] = useState(() => filters.q || '');
    const [sort, setSort] = useState(() => filters.sort);
    const [dir, setDir] = useState(() => filters.dir);

    const firstRender = useRef(true);

    const handleSort = (colName: string) => {
        if (sort === colName) {
            setDir(dir === 'asc' ? 'desc' : 'asc');
        } else {
            setSort(colName);
            setDir('asc');
        }
    };

    useEffect(() => {
        if (firstRender.current) {
            firstRender.current = false;
            return; // skip first request
        }

        if ((sort.length > 0 && dir.length > 0) || searchQuery.length > 0 || activeFilters.length > 0) {
            // console.log(sort, dir, searchQuery, activeFilters)
            const handler = setTimeout(() => {
                const filterParams = activeFilters.reduce(
                    (acc, filter) => {
                        if (filter.value && Array.isArray(filter.value) && filter.value.length > 0) {
                            const joined =
                                filter.value.length > 1
                                    ? filter.value.join(",")
                                    : filter.value.toString();
                            acc[`${prefix}filter[${filter.field}]`] = filter.operator
                                ? `${filter.operator}:${joined}`
                                : joined;
                        } else if (filter.value) {
                            acc[`${prefix}filter[${filter.field}]`] = filter.operator
                                ? `${filter.operator}:${filter.value}`
                                : (filter.value as string);
                        }
                        return acc;
                    },
                    {} as Record<string, string>
                );

                const params =
                    Object.keys(filterParams).length > 0 ? filterParams : {};

                const routeUrl = data.tableRoute
                    ? data.tableRoute
                    : route(`${data.baseRoute}.index`);
                const searchParam = prefix + "q";
                const sortByParam = prefix + "sort";
                const sortDirParam = prefix + "dir";

                router.get(
                    routeUrl,
                    {
                        ...(params ? { ...params } : {}),
                        [searchParam]: searchQuery,
                        [sortByParam]: sort,
                        [sortDirParam]: dir,
                    },
                    {
                        preserveScroll: true,
                        preserveState: true,
                        only: [name],
                    }
                );
            }, 350);

            // cleanup: if there is changed before 250ms, clear old timeout
            return () => clearTimeout(handler);
        }
    }, [sort, dir, searchQuery, activeFilters, prefix]);

    useEffect(() => {
        if (flash?.success) {
            toast.success('success', {
                position: 'top-center',
                description: flash.success,
            });
        }
        if (flash?.error) {
            toast.error('error', {
                position: 'top-center',
                description: flash.error,
            });
        }
    }, [flash]);

    const toggleSelectAll = (checked: boolean) => {
        if (checked) {
            const visibleIds = items.data.map((item) => item.id as string | number);
            const mergeIds = Array.from(new Set([...visibleIds, ...selectedIds]));
            setSelectedIds(mergeIds);
        } else {
            setSelectedIds([]);
        }
    };

    const toggleSelectOne = (id: string | number) => {
        setSelectedIds((prev) => (prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]));
    };

    const handleAddFilter = (field: string) => {
        const filterExists = activeFilters.some((filter) => filter.field === field);

        if (!filterExists) {
            const filterDef = filters.opt?.find((f) => f.field === field);
            if (!filterDef) return;

            const newFilter: ActiveFilter = {
                field,
                value: filterDef.type === 'select' && filterDef.multiple ? [] : '',
                operator: filterDef.operators[0]?.value ?? '',
            };

            setActiveFilters((prev) => [...prev, newFilter]);
            openPopover(field);
            activeFilters
                .filter((filter) => filter.field !== field)
                .forEach((filter) => {
                    closePopover(filter.field);
                });
            return;
        }
        openPopover(field);
        activeFilters
            .filter((filter) => filter.field !== field)
            .forEach((filter) => {
                closePopover(filter.field);
            });
    };

    const removeFilter = (field: string) => {
        const newFilters = activeFilters.filter((f) => f.field !== field);
        setActiveFilters(newFilters);
    };

    return (
        <div className="overflow-hidden rounded-xl border bg-background text-foreground shadow-sm">
            <AppDataTableToolbar
                searchQuery={searchQuery}
                setSearchQuery={setSearchQuery}
                selectedIds={selectedIds}
                activeFilters={activeFilters}
                handleAddFilter={handleAddFilter}
                columns={columns}
                toggleColumn={toggleColumn}
                hiddenColumns={hiddenColumns}
                data={data}
            >
                {children && children.toolbarAction}
            </AppDataTableToolbar>
            <AppDataTableActiveFilters
                name={name}
                activeFilters={activeFilters}
                setActiveFilters={setActiveFilters}
                filters={filters}
                removeFilter={removeFilter}
                openFilterPopovers={openFilterPopovers}
                openPopover={openPopover}
                closePopover={closePopover}
            />

            <AppDataTableContent
                items={items}
                columns={columns}
                selectedIds={selectedIds}
                hiddenColumns={hiddenColumns}
                sort={sort}
                dir={dir}
                handleSort={handleSort}
                toggleSelectAll={toggleSelectAll}
                toggleSelectOne={toggleSelectOne}
                disablePagination={disablePagination}
            >
                {children && children.rowAction}
            </AppDataTableContent>

            {!disablePagination && (
                <AppDataTablePagination
                    data={data}
                    selectedIds={selectedIds}
                    toggleSelectAll={toggleSelectAll}
                />
            )}
        </div>
    );
}
