// src/Stubs/vue/resources/js/components/builder/field/AppFieldBuilderMarkdown.vue
<script lang="ts" setup>
import { ref, watch } from 'vue';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';
import { cn } from '@/lib/utils';
import { FieldDefinition } from '@/types/field-builder';
import { marked } from 'marked';

interface Props {
    field: FieldDefinition;
    modelValue?: string;
    idx: string;
}

const props = defineProps<Props>();
const model = defineModel<typeof props.modelValue>();

const tab = ref<'write' | 'preview'>('write');
const textareaRef = ref<HTMLTextAreaElement | null>(null);

watch(tab, (newTab) => {
    if (newTab === 'write') {
        textareaRef.value?.focus();
    }
});

</script>

<template>
    <div class="space-y-1">
        <Tabs v-model="tab">
            <TabsList class="mb-2">
                <TabsTrigger class="hover:cursor-pointer" value="write">Write</TabsTrigger>
                <TabsTrigger class="hover:cursor-pointer" value="preview">Preview</TabsTrigger>
            </TabsList>

            <TabsContent value="write">
                <Textarea :id="props.field.key" v-model="model" ref="textareaRef"
                    :placeholder="'Write markdown here...'" :rows="10" :class="props.field.mergeClass"
                    :disabled="props.field.isDisable" />
            </TabsContent>

            <TabsContent value="preview">
                <div :class="cn('prose-sm dark:prose-dark max-w-none p-3 border rounded bg-muted')"
                    v-html="marked.parse(modelValue || '')" />
            </TabsContent>
        </Tabs>
    </div>
</template>

// src/Stubs/resources/js/components/builder/app-field-builder-markdown.tsx
import {useEffect, useRef, useState} from 'react';
import {Textarea} from '@/components/ui/textarea';
import {Tabs, TabsList, TabsTrigger, TabsContent} from '@/components/ui/tabs';
import {cn} from '@/lib/utils';
import {marked} from 'marked';

type Props = {
    field: {
        name: string;
        label: string;
        type: string;
        placeholder?: string;
        mergeClass?: string;
    };
    value: string;
    setData: (key: string, value: string) => void;
};

export function AppFieldBuilderMarkdown({field, value, setData}: Props) {
    const [tab, setTab] = useState<'write' | 'preview'>('write');
    const textareaRef = useRef<HTMLTextAreaElement>(null);

    useEffect(() => {
        if (tab === 'write') {
            textareaRef.current?.focus();
        }
    }, [tab]);

    const handleChange = (e: React.ChangeEvent<HTMLTextAreaElement>) => {
        setData(field.name, e.target.value);
    };

    return (
        <div className="space-y-1">
            <Tabs value={tab} onValueChange={(val) => setTab(val as 'write' | 'preview')}>
                <TabsList className="mb-2">
                    <TabsTrigger value="write">Write</TabsTrigger>
                    <TabsTrigger value="preview">Preview</TabsTrigger>
                </TabsList>

                <TabsContent value="write">
                    <Textarea
                        id={field.name}
                        value={value}
                        onChange={handleChange}
                        placeholder="Write markdown here..."
                        rows={10}
                        className={field.mergeClass}
                    />
                </TabsContent>

                <TabsContent value="preview">
                    <div
                        className={cn("prose-sm dark:prose-dark max-w-none p-3 border rounded bg-muted")}
                        dangerouslySetInnerHTML={{__html: marked.parse(value || '')}}
                        placeholder={field.placeholder || 'Write markdown content here...'}
                    />
                </TabsContent>
            </Tabs>
        </div>
    );
}
