// src/Stubs/vue/resources/js/components/builder/field/checkbox/AppFieldBuilderCheckboxList.vue
<script setup lang="ts">
import { Checkbox } from '@/components/ui/checkbox'
import { Label } from '@/components/ui/label'
import { gridClasses } from '@/lib/utils'
import type { FieldDefinition } from '@/types/field-builder'
import { computed } from 'vue'

interface Props {
    field: FieldDefinition
    modelValue?: Array<string | number> | null | undefined
    idx: string
}

const props = defineProps<Props>()
const model = defineModel<typeof props.modelValue>()

function isChecked(value: string | number) {
    return computed({
        get: () => model.value?.includes(value) ?? false,
        set: (checked: boolean) => {
            if (!model.value) model.value = []
            if (checked) {
                if (!model.value.includes(value)) {
                    model.value = [...model.value, value]
                }
            } else {
                model.value = model.value.filter(v => v !== value)
            }
        }
    })
}
</script>

<template>
    <div :class="`space-y-2 gap-2 ${gridClasses(props.field.gridCol)}`">
        <template v-if="props.field.options?.length">
            <div v-for="option in props.field.options" :key="props.field.key + option.value.toString()"
                class="flex items-center space-x-2">
                <Checkbox
                    :id="`${props.field.key}-${option.value}`"
                    v-model="isChecked(option.value.toString()).value"
                    :class="props.field.mergeClass"
                    :disabled="props.field.isDisable"
                />
                <Label :for="`${props.field.key}-${option.value}`" class="text-sm font-normal">
                    {{ option.label }}
                </Label>
            </div>
        </template>

        <div v-else class="text-sm text-muted-foreground italic">
            {{ props.field.placeholder || 'No options available' }}
        </div>
    </div>
</template>

// src/Stubs/resources/js/components/builder/app-field-builder-checkbox-list.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import React from 'react';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { FieldDefinition } from "@/types/field-builder";
import { gridClasses } from "@/lib/utils";

interface CheckboxListFieldProps {
    field: FieldDefinition;
    value: any;
    onChange: (name: string, value: any, operator?: string) => void;
}

export function AppFieldBuilderCheckboxList({ field, value, onChange }: CheckboxListFieldProps) {
    // Ensure value is an array
    const selectedValues = Array.isArray(value) ? value : (value ? [value] : []);

    const handleCheckboxChange = (checkboxValue: string | number | boolean, checked: boolean) => {
        let newValues: any[];

        if (checked) {
            // Add value if it's not already selected
            newValues = [...selectedValues, checkboxValue];
        } else {
            // Remove value if it's currently selected
            newValues = selectedValues.filter(v => v !== checkboxValue);
        }

        onChange(field.name, newValues);
    };

    return (
        <div className={`space-y-2 gap-2 ${gridClasses(field.gridCol)}`}>
            {field.options?.map((option) => (
                <div key={field.key + option.value.toString()} className="flex items-center space-x-2">
                    <Checkbox
                        id={`${field.name}-${option.value}`}
                        checked={selectedValues.includes(option.value)}
                        onCheckedChange={(checked) => handleCheckboxChange(option.value, !!checked)}
                        className={field.mergeClass}
                        disabled={field.isDisable}
                    />
                    <Label
                        htmlFor={`${field.name}-${option.value}`}
                        className="text-sm font-normal"
                    >
                        {option.label}
                    </Label>
                </div>
            ))}

            {field.options?.length === 0 && (
                <div className="text-sm text-muted-foreground italic">
                    {field.placeholder || 'No options available'}
                </div>
            )}
        </div>
    );
}
