// src/Stubs/vue/resources/js/components/builder/field/AppFieldBuilderCustom.vue
<script lang="ts" setup>
import { ref, onMounted } from 'vue';
import { customFieldsComponents } from '@/components/builder/custom-fields';
import { cn } from '@/lib/utils';
import { useFormStore } from '@/stores/form';
import { FieldDefinition } from '@/types/field-builder';

interface Props {
    field: FieldDefinition;
    modelValue: any;
    idx: string;
}

const props = defineProps<Props>();
const store = useFormStore(props.idx)();

const initialized = ref(false);

onMounted(() => {
    if (!initialized.value && props.modelValue === undefined && props.field.state !== undefined) {
        store.onReactive(props.field.key, props.field.state);
        initialized.value = true;
    }
});

const Component = props.field.component
    ? customFieldsComponents[props.field.component]
    : null;
</script>

<template>
    <div v-if="Component" :class="cn('space-y-2', field.mergeClass)">
        <component :is="Component" :field="field" :idx="idx"
            :modelValue="modelValue"
            v-bind="field.extraAttributes" />
    </div>

    <div v-else-if="field.component" class="text-sm text-destructive">
        Custom component '{{ field.component }}' not found. Make sure to register it using
        registerCustomComponent.
    </div>

    <div v-else class="text-sm text-amber-500 p-3 bg-amber-50 rounded-md border border-amber-200">
        No component specified for custom field '{{ field.key }}'. Use the 'component' property to specify a Vue
        component.
    </div>
</template>

// src/Stubs/resources/js/components/builder/app-field-builder-custom.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import { useEffect, useState } from 'react';
import { cn } from '@/lib/utils';
import { customFieldsComponents } from '@/components/custom-fields';

export function AppFieldBuilderCustom({ field, value, setData, error }: any) {
    // Use field state as initial value if provided and no value exists yet
    const [initialized, setInitialized] = useState(false);

    useEffect(() => {
        // Initialize state from field.state if value is undefined
        if (!initialized && value === undefined && field.state !== undefined) {
            setData(field.name, field.state);
            setInitialized(true);
        }
    }, [initialized, field.name, field.state, value, setData]);

    // Render the custom component if specified
    if (field.component) {
        const Component = customFieldsComponents[field.component];

        if (Component) {
            return (
                <div className={cn('space-y-2', field.mergeClass)}>
                    <Component
                        name={field.name}
                        label={field.label}
                        value={value ?? field.state}
                        onChange={(newValue: any) => setData(field.name, newValue)}
                        error={error}
                        {...(field.extraAttributes || {})}
                    />
                </div>
            );
        } else {
            return (
                <div className="text-sm text-destructive">
                    Custom component '{field.component}' not found. Make sure to register it using registerCustomComponent.
                </div>
            );
        }
    }

    // If no component is specified, show a message
    return (
        <div className="text-sm text-amber-500 p-3 bg-amber-50 rounded-md border border-amber-200">
            No component specified for custom field '{field.name}'. Use the 'component' property to specify a React component.
        </div>
    );
}
