// src/Stubs/resources/js/components/builder/app-field-builder-flatpickr.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import React, {useCallback, useEffect, useRef} from 'react';
import {Input} from '@/components/ui/input';
import flatpickr from 'flatpickr';
import 'flatpickr/dist/themes/dark.css';
import {cn} from "@/lib/utils";
import {format, parse} from "date-fns";
import {FieldDefinition} from "@/types/field-builder";

interface FlatpickrFieldProps {
    field: FieldDefinition;
    value: any;
    operator?: string;
    onChange: (name: string, value: any, operator?: string) => void;
}

export function AppFieldBuilderFlatpickr({field, value, operator, onChange}: FlatpickrFieldProps) {
    const operatorRef = useRef(operator);
    operatorRef.current = operator;

    const inputRef = useRef<HTMLInputElement>(null);
    const flatpickrInstance = useRef<any>(null);

    const parseValue = useCallback((val: any): Date | null | Array<Date | null> => {
        if (!val) return null;

        if (val instanceof Date && !isNaN(val.getTime())) {
            return val;
        }

        const parseSingleDate = (dateStr: string): Date | null => {
            const trimmedDateStr = dateStr.trim();
            if (!trimmedDateStr) return null;

            // First, try parsing by standardizing the string for new Date()
            // This handles 'YYYY-MM-DD HH:mm:ss' by replacing the space with a 'T',
            // making it a format that new Date() can parse reliably across browsers.
            const standardizedDateStr = trimmedDateStr.replace(' ', 'T');
            const date = new Date(standardizedDateStr);
            if (!isNaN(date.getTime())) {
                return date;
            }

            // If native parsing fails, fall back to date-fns for specific formats.
            try {
                const parsedDate = parse(
                    trimmedDateStr,
                    field.withTime === false ? 'yyyy-MM-dd' : 'yyyy-MM-dd HH:mm:ss',
                    new Date()
                );

                if (!isNaN(parsedDate.getTime())) {
                    return parsedDate;
                }
            } catch {
                // date-fns parse can throw on weird inputs, though it usually returns Invalid Date.
            }

            console.warn('Failed to parse date:', trimmedDateStr);
            return null;
        };

        if (typeof val === 'string') {
            if (val.includes(',')) {
                return val.split(',').map(v => parseSingleDate(v));
            }
            return parseSingleDate(val);
        }

        return null;
    }, [field.withTime]);

    useEffect(() => {
        if (!inputRef.current) return;

        const defaultConfig = {
            onChange: (selectedDates: Date[], dateStr: string, instance: any) => {
                // console.log(selectedDates, dateStr, instance);
                const currentOperator = operatorRef.current;
                if (
                    (instance.config.mode === 'range') &&
                    selectedDates.length < 2
                ) {
                    return;
                }

                if (selectedDates.length > 1) {
                    instance.close();
                    if (field.utcConvert === false) {
                        const formattedOne = format(
                            selectedDates[0],
                            field.withTime === false ? 'yyyy-MM-dd' : 'yyyy-MM-dd HH:mm:ss'
                        );
                        const formattedTwo = format(
                            selectedDates[1],
                            field.withTime === false ? 'yyyy-MM-dd' : 'yyyy-MM-dd HH:mm:ss'
                        );
                        onChange(field.name, `${formattedOne},${formattedTwo}`, currentOperator);
                        return;
                    }
                    const tmpValue = `${selectedDates[0].toISOString()},${selectedDates[1].toISOString()}`;
                    onChange(field.name, tmpValue, currentOperator);
                } else if (selectedDates.length == 1) {
                    if (field.utcConvert === false) {
                        const formatted = format(
                            selectedDates[0],
                            field.withTime === false ? 'yyyy-MM-dd' : 'yyyy-MM-dd HH:mm:ss'
                        );
                        onChange(field.name, formatted, currentOperator);
                        return;
                    }
                    onChange(field.name, selectedDates[0].toISOString(), currentOperator);
                } else {
                    onChange(field.name, null, currentOperator);
                }
            },
        };

        let config = {...defaultConfig, ...field.config};
        if (operatorRef.current === '><' || operatorRef.current === '!><') {
            config = {...config, ...{mode: 'range'}};
        }
        flatpickrInstance.current = flatpickr(inputRef.current, config);

        const initialDate = parseValue(value);
        if (initialDate) {
            flatpickrInstance.current.setDate(initialDate);
        }

    }, [field.config, field.name, operator, field.utcConvert, field.withTime, parseValue, onChange, value]);

    useEffect(() => {
        if (flatpickrInstance.current && flatpickrInstance.current.operator !== operatorRef.current) {
            flatpickrInstance.current.clear();
        }
    }, [operator]);

    return (
        <div>
            <Input
                ref={inputRef}
                id={field.name}
                name={field.name}
                placeholder={field.placeholder || 'Pick a date'}
                readOnly
                autoComplete="off"
                className={cn("cursor-pointer", field.mergeClass)}
                disabled={field.isDisable}
            />
        </div>
    );
}

// src/Stubs/vue/resources/js/components/builder/field/AppFieldBuilderFlatpickr.vue
<script lang="ts" setup>
import { ref, watch, onMounted } from 'vue';
import { cn } from '@/lib/utils';
import { FieldDefinition } from '@/types/field-builder';
import flatpickr from 'flatpickr';
import 'flatpickr/dist/themes/dark.css';
import { format, parse } from 'date-fns';
import { useFormStore } from '@/stores/form';

interface Props {
    field: FieldDefinition;
    modelValue?: any;
    idx: string;
}

const props = defineProps<Props>();
const store = useFormStore(props.idx)();

const inputRef = ref<HTMLInputElement | null>(null);
let fpInstance: flatpickr.Instance | null = null;

const parseValue = (val: any): Date | null | Array<Date | null> => {
    if (!val) return null;

    const parseSingleDate = (dateStr: string): Date | null => {
        const trimmed = dateStr.trim();
        if (!trimmed) return null;

        const standardized = trimmed.replace(' ', 'T');
        const date = new Date(standardized);
        if (!isNaN(date.getTime())) return date;

        try {
            const parsed = parse(
                trimmed,
                props.field.withTime === false ? 'yyyy-MM-dd' : 'yyyy-MM-dd HH:mm:ss',
                new Date()
            );
            if (!isNaN(parsed.getTime())) return parsed;
        } catch { }
        console.warn('Failed to parse date:', trimmed);
        return null;
    };

    if (typeof val === 'string') {
        if (val.includes(',')) return val.split(',').map(parseSingleDate);
        return parseSingleDate(val);
    }

    return null;
};

onMounted(() => {
    if (!inputRef.value) return;

    const config: any = {
        enableTime: props.field.withTime !== false,
        time_24hr: true,
        dateFormat: props.field.withTime === false ? 'Y-m-d' : 'Y-m-d H:i:S',
        minuteIncrement: 1,
        allowInput: false,
        onClose: (selectedDates: Date[]) => {
            if (!selectedDates.length) return;
            if (selectedDates.length === 1 && props.field.withTime) {
                if (props.field.utcConvert === false) {
                    const formatted = format(selectedDates[0], 'yyyy-MM-dd HH:mm:ss');
                    store.onReactive(props.field.key, formatted);
                    return;
                }
                store.onReactive(props.field.key, selectedDates[0].toISOString());
            }
        },
        onChange: (selectedDates: Date[], dateStr: string, instance: any) => {
            if (instance.config.mode === 'range' && selectedDates.length < 2) return;

            if (selectedDates.length > 1) {
                instance.close();
                if (props.field.utcConvert === false) {
                    const formattedOne = format(
                        selectedDates[0],
                        props.field.withTime === false ? 'yyyy-MM-dd' : 'yyyy-MM-dd HH:mm:ss'
                    );
                    const formattedTwo = format(
                        selectedDates[1],
                        props.field.withTime === false ? 'yyyy-MM-dd' : 'yyyy-MM-dd HH:mm:ss'
                    );
                    store.onReactive(props.field.key, `${formattedOne},${formattedTwo}`);
                    return;
                }
                store.onReactive(props.field.key, `${selectedDates[0].toISOString()},${selectedDates[1].toISOString()}`);
            } else if (selectedDates.length === 1 && props.field.withTime === false) {
                if (props.field.utcConvert === false) {
                    const formatted = format(selectedDates[0], 'yyyy-MM-dd');
                    store.onReactive(props.field.key, formatted);

                    return;
                }
                store.onReactive(props.field.key, selectedDates[0].toISOString());
            } else if (!selectedDates.length) {
                store.onReactive(props.field.key, null);
            }
            // console.log(selectedDates, dateStr, selectedDates.length, props.field);
        },
    };

    fpInstance = flatpickr(inputRef.value, { ...config, ...props.field.config });

    const initialDate = parseValue(props.modelValue);
    const cleanDate = Array.isArray(initialDate)
        ? initialDate.filter((d): d is Date => d instanceof Date)
        : initialDate instanceof Date
            ? initialDate
            : null;

    if (fpInstance && cleanDate) fpInstance.setDate(cleanDate);
});

watch(() => props.modelValue, (newVal) => {
    const initialDate = parseValue(newVal);
    const cleanDate = Array.isArray(initialDate)
        ? initialDate.filter((d): d is Date => d instanceof Date)
        : initialDate instanceof Date
            ? initialDate
            : null;

    if (fpInstance && cleanDate) fpInstance.setDate(cleanDate);
});
</script>

<template>
    <div>
        <input
              ref="inputRef"
              type="text"
              autocomplete="off"
              :id="props.field.key"
              :name="props.field.key"
              :placeholder="props.field.placeholder || 'Pick a date'"
              :disabled="props.field.isDisable"
              :class="cn('w-full rounded-md border border-gray-300 bg-white text-sm px-3 py-2 shadow-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500 disabled:cursor-not-allowed disabled:opacity-50 dark:bg-gray-800 dark:border-gray-700 dark:text-gray-100 dark:placeholder-gray-400', props.field.mergeClass)"
              readonly
            />
    </div>
</template>
