// src/Stubs/resources/js/components/builder/app-field-builder-key-value.tsx
/* eslint-disable @typescript-eslint/no-explicit-any */
import React, { useState } from 'react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { PlusCircle, Trash2, GripVertical } from 'lucide-react';
import { cn } from '@/lib/utils';
import { FieldDefinition } from '@/types/field-builder';

interface KeyValueFieldProps {
    field: FieldDefinition;
    value: Record<string, string> | null;
    onChange: (name: string, value: any, operator?: string) => void;
    error?: string | Record<string, string>;
}

export function AppFieldBuilderKeyValue({ field, value, onChange, error }: KeyValueFieldProps) {
    // Convert object to array of key-value pairs for easier manipulation
    const [items, setItems] = useState<Array<{ key: string; value: string }>>(() => {
        if (!value) return [];
        return Object.entries(value).map(([key, val]) => ({ key, value: String(val) }));
    });

    const [draggedIndex, setDraggedIndex] = useState<number | null>(null);

    // Update the form data whenever items change
    const updateData = (newItems: Array<{ key: string; value: string }>) => {
        // Convert array back to object
        const newData = newItems.reduce((acc, { key, value }) => {
            if (key.trim()) {
                acc[key] = value;
            }
            return acc;
        }, {} as Record<string, string>);

        setItems(newItems);
        onChange(field.name, newData);
    };

    const addItem = () => {
        const newItems = [...items, { key: '', value: '' }];
        updateData(newItems);
    };

    const removeItem = (index: number) => {
        const newItems = [...items];
        newItems.splice(index, 1);
        updateData(newItems);
    };

    const updateItem = (index: number, keyOrValue: 'key' | 'value', newValue: string) => {
        const newItems = [...items];
        newItems[index][keyOrValue] = newValue;
        updateData(newItems);
    };

    const moveItem = (fromIndex: number, toIndex: number) => {
        if (toIndex < 0 || toIndex >= items.length) return;

        const newItems = [...items];
        const [movedItem] = newItems.splice(fromIndex, 1);
        newItems.splice(toIndex, 0, movedItem);

        updateData(newItems);
    };

    const handleDragStart = (index: number) => {
        setDraggedIndex(index);
    };

    const handleDragOver = (e: React.DragEvent, index: number) => {
        e.preventDefault();
        if (draggedIndex === null || draggedIndex === index) return;

        moveItem(draggedIndex, index);
        setDraggedIndex(index);
    };

    const handleDragEnd = () => {
        setDraggedIndex(null);
    };

    return (
        <div className="space-y-2">
            <div className="rounded-md border">
                {/* Header */}
                <div className="flex items-center p-2 bg-muted/40 border-b">
                    {field.reorderable && <div className="w-8" />}
                    <div className="flex-1 font-medium text-sm">{field.keyLabel || 'Key'}</div>
                    <div className="flex-1 font-medium text-sm">{field.valueLabel || 'Value'}</div>
                    {field.removable && <div className="w-8" />}
                </div>

                {/* Items */}
                <div className="divide-y">
                    {items.length === 0 && (
                        <div className="p-4 text-center text-sm text-muted-foreground italic">
                            No items added yet.
                        </div>
                    )}

                    {items.map((item, index) => (
                        <div
                            key={index}
                            className={cn(
                                'flex items-center p-2 gap-2',
                                draggedIndex === index && 'bg-muted/20'
                            )}
                            draggable={field.reorderable}
                            onDragStart={() => handleDragStart(index)}
                            onDragOver={(e) => handleDragOver(e, index)}
                            onDragEnd={handleDragEnd}
                        >
                            {field.reorderable && (
                                <div className="flex-none cursor-move">
                                    <GripVertical className="h-4 w-4 text-muted-foreground" />
                                </div>
                            )}

                            <Input
                                className="flex-1"
                                value={item.key}
                                onChange={(e) => updateItem(index, 'key', e.target.value)}
                                placeholder={field.keyPlaceholder || 'Enter key'}
                                disabled={!field.editable}
                            />

                            <Input
                                className="flex-1"
                                value={item.value}
                                onChange={(e) => updateItem(index, 'value', e.target.value)}
                                placeholder={field.valuePlaceholder || 'Enter value'}
                                disabled={!field.editable}
                            />

                            {field.removable && (
                                <Button
                                    type="button"
                                    variant="ghost"
                                    size="icon"
                                    className="flex-none h-8 w-8 text-destructive hover:text-destructive hover:bg-destructive/10"
                                    onClick={() => removeItem(index)}
                                >
                                    <Trash2 className="h-4 w-4" />
                                </Button>
                            )}
                        </div>
                    ))}
                </div>
            </div>

            {field.addable && (
                <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={addItem}
                    className="mt-2"
                    disabled={field.isDisable}
                >
                    <PlusCircle className="h-4 w-4 mr-2" />
                    {field.addButtonLabel || 'Add Item'}
                </Button>
            )}

        </div>
    );
}

// src/Stubs/vue/resources/js/components/builder/field/AppFieldBuilderKeyValue.vue
<script lang="ts" setup>
import { ref, watch } from 'vue';
import { FieldDefinition } from '@/types/field-builder';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { GripVertical, PlusCircle, Trash2 } from 'lucide-vue-next';
// import { useFormStore } from '@/stores/form';

interface Props {
    field: FieldDefinition;
    modelValue: Record<string, string> | null;
    idx: string;
}

const props = defineProps<Props>();
const model = defineModel<typeof props.modelValue>();
// const store = useFormStore(props.idx)();

// Convert object to array for internal state
const items = ref<Array<{ key: string; value: string }>>(
    Object.entries(props.modelValue || {}).map(([key, val]) => ({ 
        key, 
        value: String(val) 
    }))
);

// Update both model and store
const updateData = (newItems: Array<{ key: string; value: string }>) => {
    const newData = newItems.reduce((acc, { key, value }) => {
        if (key.trim()) acc[key] = value;
        return acc;
    }, {} as Record<string, string>);
    items.value = newItems;
    model.value = newData;
};

const addItem = () => {
    const newItems = [...items.value, { key: '', value: '' }];
    updateData(newItems);
};

const removeItem = (index: number) => {
    const newItems = [...items.value];
    newItems.splice(index, 1);
    updateData(newItems);
};

// const updateItem = (index: number, keyOrValue: 'key' | 'value', newValue: string) => {
//     const newItems = [...items.value];
//     newItems[index][keyOrValue] = newValue;
//     items.value = newItems; // trigger items watcher
// };

const moveItem = (fromIndex: number, toIndex: number) => {
    if (toIndex < 0 || toIndex >= items.value.length) return;
    const newItems = [...items.value];
    const [movedItem] = newItems.splice(fromIndex, 1);
    newItems.splice(toIndex, 0, movedItem);
    updateData(newItems);
};
const draggedIndex = ref<number | null>(null);
const handleDragStart = (index: number) => (draggedIndex.value = index);
const handleDragOver = (e: DragEvent, index: number) => {
    e.preventDefault();
    if (draggedIndex.value === null || draggedIndex.value === index) return;
    moveItem(draggedIndex.value, index);
    draggedIndex.value = index;
};
const handleDragEnd = () => (draggedIndex.value = null);

// Watch external changes
watch(() => props.modelValue, (newVal) => {
    if (newVal && JSON.stringify(newVal) !== JSON.stringify(model.value)) {
        items.value = Object.entries(newVal).map(([key, val]) => ({ 
            key, 
            value: String(val) 
        }));
    }
}, { deep: true });
</script>

<template>
    <div class="space-y-2">
        <div class="rounded-md border">
            <!-- Header -->
            <div class="flex items-center p-2 bg-muted/40 border-b">
                <div v-if="props.field.reorderable" class="w-8" />
                <div class="flex-1 font-medium text-sm">{{ props.field.keyLabel || 'Key' }}</div>
                <div class="flex-1 font-medium text-sm">{{ props.field.valueLabel || 'Value' }}</div>
                <div v-if="props.field.removable" class="w-8" />
            </div>

            <!-- Items -->
            <div class="divide-y">
                <div v-if="items.length === 0" class="p-4 text-center text-sm text-muted-foreground italic">
                    No items added yet.
                </div>

                <div v-for="(item, index) in items" :key="index" class="flex items-center p-2 gap-2"
                    :class="draggedIndex === index ? 'bg-muted/20' : ''" :draggable="props.field.reorderable"
                    @dragstart="handleDragStart(index)" @dragover.prevent="handleDragOver($event, index)"
                    @dragend="handleDragEnd">
                    <div v-if="props.field.reorderable" class="flex-none cursor-move">
                        <GripVertical class="h-4 w-4 text-muted-foreground" />
                    </div>

                    <Input class="flex-1" 
                        v-model="item.key"
                        :placeholder="props.field.keyPlaceholder || 'Enter key'"
                        :disabled="!props.field.editable || props.field.isDisable"
                        @change="updateData(items)" 
                    />

                    <Input class="flex-1" 
                        v-model="item.value"
                        :placeholder="props.field.valuePlaceholder || 'Enter value'"
                        :disabled="!props.field.editable || props.field.isDisable"
                        @change="updateData(items)"
                    />

                    <Button v-if="props.field.removable" type="button" variant="ghost" size="icon"
                        class="flex-none h-8 w-8 text-destructive hover:text-destructive hover:bg-destructive/10"
                        @click="removeItem(index)" :disabled="props.field.isDisable">
                        <Trash2 class="h-4 w-4" />
                    </Button>
                </div>
            </div>
        </div>

        <Button v-if="props.field.addable" type="button" variant="outline" size="sm" class="mt-2" @click="addItem"
            :disabled="props.field.isDisable">
            <PlusCircle class="h-4 w-4 mr-2" />
            {{ props.field.addButtonLabel || 'Add Item' }}
        </Button>
    </div>
</template>
