// src/Stubs/vue/resources/js/pages/builder/show.vue
<script lang="ts" setup>
import { Head } from '@inertiajs/vue3';
import AppLayout from "@/layouts/AppLayout.vue";
import AppFormBuilder from "@/components/builder/AppFormBuilder.vue";
import { Card, CardContent } from "@/components/ui/card";
import AppFormBuilderAction from "@/components/builder/form/AppFormBuilderAction.vue";
import { route } from "ziggy-js";
import type { Form } from '@/types/form';
import type { BreadcrumbItem } from "@/types";
import { useFormStore } from '@/stores/form';

// Props
interface Props {
    form: Form;
}
const props = defineProps<Props>();

const { baseRoute, routeId, title, prefix } = props.form;

const idx = `${prefix}-show}`;
const store = useFormStore(idx)();
store.setData(props.form);

const breadcrumbs: BreadcrumbItem[] = [
    { title: title, href: route(baseRoute + ".index") },
    { title: 'show', href: route(baseRoute + ".show", routeId) },
    { title: `#${routeId}`, href: '' },
];

</script>

<template>
    <AppLayout :breadcrumbs="breadcrumbs">

        <Head :title="`show ${title} #${routeId}`" />
        <div class="p-4">
            <Card class="p-4 max-w-full">
                <CardContent>
                    <AppFormBuilder :form="props.form" :idx="idx">
                        <template #formAction>
                            <AppFormBuilderAction :form="props.form" :idx="idx" />
                        </template>
                    </AppFormBuilder>
                </CardContent>
            </Card>
        </div>
    </AppLayout>
</template>

// src/Stubs/resources/js/pages/builder/show.tsx
import { Head } from '@inertiajs/react';
import AppLayout from "@/layouts/app-layout";
import { BreadcrumbItem } from "@/types";
import { ColumnDef, FieldDefinition } from "@/types/field-builder";
import { AppFormBuilder } from "@/components/builder/app-form-builder";
import { Card, CardContent } from "@/components/ui/card";
import { route } from "ziggy-js";

type Form = {
    columns: ColumnDef;
    fields: FieldDefinition[];
};

type PageProps = {
    form: Form;
    routeName: string;
    routeId?: string;
    formClass: string;
};

export default function Show({ form, routeName, routeId, formClass }: PageProps) {
    const { columns, fields } = form;
    const breadcrumbs: BreadcrumbItem[] = [
        { title: `${routeName}`, href: route(routeName + ".index") },
        { title: 'show', href: route(routeName + ".show", routeId) },
        { title: `#${routeId}`, href: '' }
    ];

    return (
        <AppLayout breadcrumbs={breadcrumbs}>
            <Head title={`show ${routeName} #${routeId}`} />
            <div className="p-4">
                <Card className="p-4 max-w-full">
                    <CardContent>
                        <AppFormBuilder columns={columns} fields={fields} routeName={routeName} routeId={routeId}
                            mode="show" formClass={formClass} />
                    </CardContent>
                </Card>
            </div>
        </AppLayout>
    );
}
